# Generated by Django 2.0.1 on 2018-02-28 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('body', models.TextField()),
            ],
        ),
    ]
