# Generated by Django 2.0.1 on 2018-05-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180513_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('mnumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(max_length=30)),
                ('occupation', models.CharField(max_length=30)),
                ('faculty', models.CharField(choices=[('I', 'Intercession'), ('T', 'Trade and Investment'), ('E', 'Economy'), ('S', 'Sounds_and_Worship'), ('D', 'Dances Poems and Arts'), ('II', 'Intercity and International Affairs'), ('IT', 'IT and Communications'), ('L', 'Leadership_and_Government'), ('SME', 'SMEs Development and Priesthood'), ('PF', 'PBC Finances Council 24')], default='I', max_length=40)),
            ],
        ),
    ]
