# Generated by Django 2.0.1 on 2018-05-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='pbc_number',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
