# Generated by Django 2.0.1 on 2018-05-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_members_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
