# Generated by Django 2.0.1 on 2018-05-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20180520_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='accept',
            field=models.BooleanField(),
        ),
    ]
