# Generated by Django 2.0.1 on 2018-05-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180520_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='Interested_PBC_Faculty',
            field=models.CharField(choices=[('I', 'Intercession'), ('T', 'Trade and Investment'), ('E', 'Economy'), ('S', 'Sounds and Worship'), ('D', 'Dances Poems and Arts'), ('II', 'Intercity and International Affairs'), ('IT', 'IT and Communications'), ('L', 'Leadership and Government'), ('SME', 'SMEs Development and Priesthood'), ('PF', 'PBC Finances Council 24')], default='I', max_length=40),
        ),
    ]
