# Generated by Django 2.0.1 on 2018-06-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='Title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss')], max_length=40),
        ),
    ]
